### ISSUE TITLE
update to more recent PuLP versions in pypi (2.3)

### ISSUE THREAD

**Issue by pchtsp** [conda-forge/pulp-feedstock#8]
Hello!

Could you please update to the latest PuLP version in pypi (2.3)?
I see PRs with updates from 2.1 and 2.2 and they are failing for some reason that I do not get. 
Feel free to reach to use if you need anything changed from our side to make it work.

**Comment by knaaptime** [comment]
hey @marcelotrevisani and/or @ocefpaf really sorry to bother, but any chance either of you knows how we get this resolved?

**Comment by marcelotrevisani** [comment]
working on it
https://github.com/conda-forge/pulp-feedstock/pull/10

**Comment by knaaptime** [comment]
thank you @marcelotrevisani !!
